### ISSUE TITLE
Vite server did not start と表示され、oviceに飛ぶことができない

### ISSUE THREAD

**Issue by 3l4l5** [punkshiraishi/oviswitch#1]
とても便利でいつも愛用させていただいております。

最近のアップデートから、oviceのアイコンをクリックしても、「Vite server did not start」と表示されて飛ぶことができなくなってしまいました。（Alt + o では飛べます）
また、マイクのon offも機能していないように思います。

対処方法などありましたら、教えていただきたいです。
よろしくお願いいたします。

**Comment by 3l4l5** [comment]
解決されました。
ありがとうございます。

**Comment by punkshiraishi** [comment]
@3l4l5 
返信できずに申し訳ありませんでした。
こちらのデプロイの仕方に問題があり、不具合が生じていました。

v2.0.1 で修正しました。

ご報告、ありがとうございました！
